# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(1800, 1, 1, 1, 2, 3)),
            preserve_default=False,
        ),
    ]
