# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pickem.models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0002_added_start_time_to_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickem.Participant', validators=[pickem.models.game_still_undecided]),
        ),
    ]
