name: Push to Amazon ECR

on:
  push:
    branches:
      - main
    paths:
      - django/**
      - pickem-react/**
      - .github/workflows/push_ecr.yml

env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: 246829496375
  ECR_REPOSITORY: pickem-django

jobs:
  release-on-push:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
        tag_name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

  build-backend:
    name: Build and Push Backend
    needs: release-on-push
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-ryanmoore-${{ github.event.repository.name }}
        aws-region: ${{ env.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        context: "{{defaultContext}}:django"
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ needs.release-on-push.outputs.tag_name }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
